### ISSUE TITLE
Nim version incorrect?

### ISSUE THREAD

**Issue by jyapayne** [oprypin/nim-random#1]
Hey, I was trying to install your library, but it says it requires nim >= 0.10.3. Is this a typo?

**Comment by oprypin** [comment]
The latest version of _nim-random_ indeed relies on the recent renames that were introduced, I think, in 0.10.0. But that doesn't explain anything. It (and the previous versions) were supposed to work just fine, but there was [a regression](https://github.com/Araq/Nim/issues/1937) introduced in the compiler somewhere along the line, which is still present in 0.10.2, so the [_devel_](https://github.com/Araq/Nim/tree/devel) version of the compiler is required, which is currently 0.10.3, and the actual 0.10.4 release will have this fix.

The only other option is to use Nim 0.9.6 (or 0.10.0 might work) with [v0.2.4](https://github.com/BlaXpirit/nim-random/releases/tag/v0.2.4).

Or... you could download the library, edit out the 2 instances of `iterator randomSample` in _random.nim_, change that version if needed, and install the library manually using `nimble install` in that folder.

**Comment by jyapayne** [comment]
Cool, thanks for the detailed info.

**Comment by oprypin** [comment]
Finally made an alternative version for 0.10.2...

https://github.com/BlaXpirit/nim-random/tree/old-compiler
