### ISSUE TITLE
Undefined reference when importing random

### ISSUE THREAD

**Issue by coffeepots** [oprypin/nim-random#10]
I am on Windows, using the latest devel nim, including the prepacked gcc from the nim-lang.org download page.

Made a new file 'randomtest.nim' and including the following code:

``` nimrod
import random
```

This causes the following linker issue:

> Hint: urandom [Processing]
> CC: randomtest
> CC: random_random
> CC: stdlib_strutils
> CC: stdlib_parseutils
> CC: stdlib_winlean
> Hint:  [Link]
> c:\nimproj\misc\nimcache\random_util.o:random_util.c:(.text+0x185): undefined reference to `@__builtin_clzll@8'
> Error: execution of an external program failed: 'gcc.exe   -o c:\nimproj\misc\randomtest.exe  c:\nimproj\misc\nimcache\random_urandom.o c:\nimproj\misc\nimcache\random_mt19937ar.o c:\nimproj\misc\nimcache\random_random_real.o c:\nimproj\misc\nimcache\random_util.o c:\nimproj\misc\nimcache\stdlib_math.o c:\nimproj\misc\nimcache\stdlib_etcpriv.o c:\nimproj\misc\nimcache\stdlib_hashes.o c:\nimproj\misc\nimcache\stdlib_intsets.o c:\nimproj\misc\nimcache\random_common.o c:\nimproj\misc\nimcache\stdlib_unsigned.o c:\nimproj\misc\nimcache\random_mersenne.o c:\nimproj\misc\nimcache\stdlib_macros.o c:\nimproj\misc\nimcache\stdlib_dynlib.o c:\nimproj\misc\nimcache\stdlib_winlean.o c:\nimproj\misc\nimcache\stdlib_parseutils.o c:\nimproj\misc\nimcache\stdlib_strutils.o c:\nimproj\misc\nimcache\stdlib_times.o c:\nimproj\misc\nimcache\random_random.o c:\nimproj\misc\nimcache\stdlib_system.o c:\nimproj\misc\nimcache\randomtest.o  '

**Comment by oprypin** [comment]
Can't reproduce.

**Comment by oprypin** [comment]
Reproduced with 32-bit build.

**Comment by oprypin** [comment]
So as it turns out, this library is broken on 32-bit, and this is just the tip of the iceberg.

**Comment by refi64** [comment]
I do not envy your pain ATM...

**Comment by coffeepots** [comment]
Oh dear, sounds like I've opened a can of worms :-( Sorry I didn't think to mention it was the 32 bit build.
Good luck to you BlaXpirit!

**Comment by oprypin** [comment]
I tried to fix this but kept running into bugs of the compiler. When I ended up fixing it, that meant changing the implementation, and some of the chi-square tests failed. The thing is, they could always fail with some probability. Or I did break something. But how would I know?
