### ISSUE TITLE
random_xorshift.o: No such file or directory

### ISSUE THREAD

**Issue by kingofoz** [oprypin/nim-random#12]
hello @BlaXpirit 
I tried the examples on the homepage , but seems they can not compile and I got the error.
I used "nimble install random" to install the package on Windows 7. Can you point where I am wrong?

**Comment by oprypin** [comment]
I don't know what, but I'm pretty sure it's something wrong with your setup. I can't help you without any details.
On Linux everythng is good, and when it comes to this library and Windows, I think nothing changed that could cause the breakage.

**Comment by kingofoz** [comment]
Basically, I got the latest nim code of devel version. Compiled it and tried to install random by "nimble install random". It installed successfully, but I can not compile the examples.
Can you please point out the setup procedure you recommend for Windows?

**Comment by kingofoz** [comment]
If possible, please have a try on Windows...
