### ISSUE TITLE
PCG PRNG Family

### ISSUE THREAD

**Issue by mbarkhau** [oprypin/nim-random#15]
How difficult would it be to implement the algorithms here?

http://www.pcg-random.org/

If you can give me some pointers I might start work on it this weekend.

**Comment by oprypin** [comment]
There are more issues with the desirability of these algorithms, than with the implementation.

Some past discussions:
- http://irclogs.nim-lang.org/17-02-2015.html#12:07:54
- https://github.com/imneme/pcg-cpp/pull/3#issuecomment-84388917

In short:
- I haven't seen any reputable sources recommending these.
- License is too complicated.
- There is a big variety of implementations and even algorithms themselves.

Implementing shouldn't be difficult. I do see that the PCG libraries have their own versions of many functions that I've implemented generically, but either way will work.

If you want to implement this, there is information on [Custom RNGs](https://github.com/BlaXpirit/nim-random#custom-rngs) and you can use existing files as examples.

---

So yeah... I'm not sure about including these. At the very least you can make an addon and use it yourself or publish it separately.

**Comment by mbarkhau** [comment]
Hmm, according to the ticket on pcg-cpp they'd be ok with swtiching to the MIT License.
