### ISSUE TITLE
Extract urandom to a separate lib?

### ISSUE THREAD

**Issue by endragor** [oprypin/nim-random#16]
Just wanted to suggest to extract `urandom` part of the lib (the one that extracts true random values from OS) into a separate library. It's quite self-sufficient and I have several applications where I need it without all of the other features of `nim-random`. I could do it myself, since this lib is MIT, but it would be fair for you to do that.

**Comment by oprypin** [comment]
Sorry (I really am sorry), but I probably will not do this. I don't think the advantages outweigh the disadvantages. 

A more interesting idea would be including that part into the standard library of Nim.

**Comment by endragor** [comment]
Could you please clarify about the disadvantages? The current direction Nim (@Araq) is taking is actually to move as much functionality as possible from stdlib into Nimble packages. So creating `urandom` Nimble package makes a lot of sense from that perspective.

**Comment by oprypin** [comment]
The egoistical disadvantage: I do not want to have 2 repositories for the same thing, as I probably won't even have time for 1.

And other than that, `urandom` is a core part of this library as it is. Having a sub-dependency is an inconvenience, even if very minor, and kinda ties the library into Nimble's infrastructure.

Regarding standard library: it's hard to find a relatively modern programming language which doesn't have `urandom` in its standard library.

Regarding the disadvantages of the current situation: what are they exactly? It's not a big deal to just not use the rest of the files. A good case could be made to at least decouple the `urandom` function, so it's not in a file that also imports the "common" module.... hm... that's actually important now that I think about it.

**Comment by endragor** [comment]
Well, at the moment one problem of having dependency on `nim-random` is that it now clashes with stdlib `random` module, so care should be taken not to accidentally import one instead of another.
But alright, if you don't want to maintain `urandom`, I'll probably just extract it later on, unless it gets into stdlib some time soon. Thank you for the explanation!

**Comment by Matceporial** [comment]
I've done it
https://github.com/Matceporial/nim-urand

**Comment by oprypin** [comment]
Isn't it in standard library by now?
