### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by saxsoares** [oprypin/nim-random#18]
Sorry for the noob question, but how can I use this library? What I have to do?

**Comment by oprypin** [comment]
You install it like any other library, and you call its functions.
If you don't know how to do some **particular** step, you ask the community. If the library's documentation is seems inadequate, you report it.

**Comment by data-man** [comment]
@saxsoares 
See unittests.
[mersenne.nim#L72](https://github.com/oprypin/nim-random/blob/master/src/random/mersenne.nim#L72) e.g.

**Comment by oprypin** [comment]
There's really no need for that, the main README has examples
