### ISSUE TITLE
Random won't compile with -d:release

### ISSUE THREAD

**Issue by jyapayne** [oprypin/nim-random#2]
Using the -d:release flag while importing random and using randomInt() causes an error. Removing the flag causes the compilation to succeed.

Here is the error:

```
/home/joey/.nimble/pkgs/random-0.3.0/random.nim(141, 9) Error: internal error: expr: var not init mtRandomBytes_164513
No stack traceback available
```

**Comment by oprypin** [comment]
Indeed... don't even know what to do with this; looks very much like a compiler bug.

Funny thing is, 0.9.4 + 0.2.4 works just fine... And that was when I did most of the testing.

**Comment by jyapayne** [comment]
I filed an issue with the nim repo here: https://github.com/Araq/Nim/issues/2023

It turns out it is a compiler bug :)

**Comment by oprypin** [comment]
The compiler has been fixed.
