### ISSUE TITLE
sample with replacement

### ISSUE THREAD

**Issue by ruqianl** [oprypin/nim-random#22]
Hi,

Is there any function for sampling with replacement, for example, the 
`iterator randomSample(interval: Slice[int]; n: Natural): int` generates the `n` elements that do not overlap. Each number has an equal chance to be picked and can be picked only once. 

My aim to generate `n` elements randomly from a set of elements with replacement. 
I have searched around, it seems the only way is to do `proc sample` on the set `n` times. I'm wondering if there is a better way (more efficient) way of doing this.

Thanks
Ruqian

**Comment by oprypin** [comment]
No, there's nothing better to be done here than calling `randomChoice` N times.
