### ISSUE TITLE
Can't shuffle at compile time

### ISSUE THREAD

**Issue by Nycto** [oprypin/nim-random#5]
Currently, this module can't be used to shuffle an array of random numbers at compile time.

Here is some sample code:

``` nimrod
import random/xorshift

proc randomArray( seed: uint64 ): array[0..255, int] =
    for i in 0..255:
        result[i] = i 
    var prng = initXorshift128Plus(seed)
    prng.shuffle(result)

const table = randomArray( 12345 )
```

The compile error is:

```
.nimble/pkgs/random-0.5.1/random/common.nim(97, 16) Error: VM is not allowed to 'cast'
```

**Comment by oprypin** [comment]
I can't do anything about this. Cast is required in this implementation. Not only shuffle is unavailable at compile time. In fact pretty much only the things that are NOT in _common.nim_ are available, because `cast` is not allowed at compile time.
