### ISSUE TITLE
Distributions

### ISSUE THREAD

**Issue by andreaferretti** [oprypin/nim-random#9]
Might it make sense to add support to draw from known distributions? Or do you think it would better be left to a separate library?

It would be nice to be able to generate random normal or Poisson data and so on.

**Comment by oprypin** [comment]
I am not sure what would be best.

The main reason this library doesn't have this is I don't have knowledge on this topic.

A separate library would work without any disadvantages. I don't know any way of generating random numbers for a distribution other than generating uniform and then converting. I'm sure there are such ways, but for simplicity of implementation I'd overlook that.

Either way, contributions are welcome.

**Comment by andreaferretti** [comment]
Yeah, I was thinking about generating uniform and then converting. It is enough to the inverse cdf of a few distributions. For the normal distribution, though, there is the following [trick](https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform)

**Comment by andreaferretti** [comment]
Just published [Alea](https://github.com/unicredit/alea) (soon to appear on Nimble)
